function H(b,c,e){function l(){0!=K&&(O=(new Date).getTime()-K)}function m(a){F=F|a;A.narme=F}function n(a){p.a("l2("+a+")");D=D|a;V()?(l(),K=0):0==K&&(K=(new Date).getTime());A.narm=D;p.a("l2e")}function h(a){P=P|a;A.naral=P}var p=new S,r=e&&e.dvObj||window.$dv,t=e&&"undefined"!==typeof e.billable||r&&r.tags[$uid]&&r.tags[$uid].billable,x=e&&e.impressionId||window.$uid,a=window.Pf||c,d=Array(a.mb),g=a.bb/a.ec+1,k=null,f="",q={},v=0,u=void 0,B=void 0,L=Array(a.mb),w={ga:{J:null,K:null,C:null,B:null,
Oe:!1},i:{u:null,s:null,L:null,M:null,F:null,G:null,o:null,m:null,Oe:!1},xa:{Fb:null,Eb:null},Mb:0},E={},y={},I,J,z={},M={},N=null;this.Ib=function(a){if(null==N||1==N||8==N)N=a};for(c=0;c<a.mb;c++)L[c]="b"+c;var C={};e&&r&&r.CommonData&&(C.ctx=e.ob,C.cmp=e.nb,C.btreg=e.I,C.btadsrv=e.Ua,C.uid=e.tb,C.brid=r.CommonData.BrowserId,C.brver=r.CommonData.BrowserVersion,C.tstype=r.CommonData.Scenario);C.jsver=b?b:null;var A={},G={},K=0,O="",Q="",P=0,D=0,F=0,R=0;this.Sc=function(){return K};this.td=function(a){R=
R|a;A.vct=R};this.sd=function(a){k=a;G.strp=k;this.sd=function(){}};this.hc=function(){return(new Date).getTime()};var W=this.hc();this.De=function(){return W};this.gf=function(){D=D&-3;F=F&-2;F&=-3};this.Hb=function(){n(2)};this.tf=function(){m(8);this.tc()};this.tc=function(){n(4)};this.od=function(){h(8);this.Hb()};this.zd=function(a){h(16);A.dbg9=a};this.Ad=function(){h(1)};this.rf=function(){this.Hb();m(1)};this.qf=function(){this.Hb();m(2)};this.gb=function(a,f){n(8);Q=p.xe(a,f)};this.mf=function(){p.a("l1");
D=D&-3;n(1);p.a("l1e")};this.rd=function(){n(16)};this.re=function(){return d};this.pd=function(f,q){x=x||e&&e.impressionId||window.$uid;var b;try{x&&r&&r.tags[x]&&r.tags[x].getTimeDiff&&(b=r.tags[x].getTimeDiff())}catch(k){}var c=b-u||100;u=b;B?200>B.length&&B.push(c):B=[];p.a("ie15");0<=f.g&&(b=Math.floor(f.g/a.ec),0<f.g%a.ec?b++:0<f.g&&b++,isNaN(d[b])&&(d[b]=0),d[b]+=Math.max(q,c),f.N&&b>=g||0==f.N&&6<=b?v+=Math.max(q,c):(timeStampTotalBuckets=v=0,this.Ib(7)));p.a("ie15e")};this.pf=function(a){var f=
a.$c;null!=a.$c&&(E.advisonl=f);null!=a.Zc&&(E.adabvvponl=a.Zc);A.dbg8="CSS1Compat"===document.compatMode?1:0;p.a("ff52");void 0!=document.documentMode&&null!=document.documentMode&&(A.dbg10=document.documentMode);p.a("ff52e")};this.eb=function(a){p.a("ie14");null!=a&&(M.adbtftopg=a)};this.nf=function(a){null!=a&&(w=a)};this.qd=function(a){p.a("ie19");this.nf(a.A);this.vf();p.a("ie19e")};this.Dd=function(){null!=w.ga.J&&(z.vptoscrx=Math.round(w.ga.J));null!=w.ga.K&&(z.vptoscry=Math.round(w.ga.K));
null!=w.ga.C&&(z.vpwdth=Math.round(w.ga.C));null!=w.ga.B&&(z.vphgt=Math.round(w.ga.B));null!=w.i.u&&(z.adtovpx=Math.round(w.i.u));null!=w.i.s&&(z.adtovpy=Math.round(w.i.s));null!=w.i.L&&(z.adtopgx=Math.round(w.i.L));null!=w.i.M&&(z.adtopgy=Math.round(w.i.M));null!=w.i.F&&(z.adtoscrx=Math.round(w.i.F));null!=w.i.G&&(z.adtoscry=Math.round(w.i.G));null!=w.xa.Fb&&(z.scrwdth=Math.round(w.xa.Fb));null!=w.xa.Eb&&(z.scrhgt=Math.round(w.xa.Eb));z.almesind=w.Mb};this.Ed=function(){if(I&&J){var a=null!=w.i.o?
w.i.o:null,f=null!=w.i.m?w.i.m:null;0>I*J&&(y.dvp_adwdth=I,y.dvp_adhgt=J,I=a,J=f)}else I=null!=w.i.o?w.i.o:null,J=null!=w.i.m?w.i.m:null;null!=I&&(y.adwdth=I);null!=J&&(y.adhgt=J)};this.vf=function(){l();for(var a=0;a<d.length;a++)d[a]&&(q[L[a]]=d[a]);this.Dd();this.Ed();p.v(z,E);p.v(z,y);p.v(z,M)};this.Qc=function(){if(1E3<=v)return!0;this.Ib(8);return!1};this.Be=function(a){var d={};x=x||e&&e.impressionId||window.$uid;var g=-1,b=p.ye();try{r&&r.tags[x]&&r.tags[x].getTimeDiff&&(g=r.tags[x].getTimeDiff())}catch(k){}var c=
[];p.v(d,C);switch(a){case 1:f=g;p.v(d,G);p.v(d,A);d.napt=O;p.v(d,z);d.dvp_log=b;d.napr=Q;t&&(d.isbmms=g,e.Bb||(d.isbmms=g,d.isgmmims=g));d.ismms=f;d.isumms=g;break;case 2:p.v(d,G);p.v(d,A);d.napt=O;p.v(d,z);d.dvp_log=b;d.napr=Q;d.isnmms=g;break;case 3:d.istoms=g,d.nvr=N;case 4:case 8:p.v(d,G);p.v(d,M);p.v(d,y);d.isbxdms=g;p.v(d,q);d.nvr=N;break;case 5:p.v(d,G);p.v(d,M);p.v(d,y);p.v(d,E);d.ismms=f||g;d.isiabvms=g;d.isuiabvms=g;break;case 6:p.v(d,M);p.v(d,y);p.v(d,E);d.ismms=f||g;d.iscvmvms=g;break;
case 16:p.v(d,G);p.v(d,A);d.napt=O;d.dvp_log=b;d.napr=Q;d.ishems=g;break;case 7:return c.join("");case 17:p.v(d,G);p.v(d,M);p.v(d,y);d.isbmms=g;d.isbvms=g;e.Bb||(d.isgmmims=g,d.isgmpims=g);break;default:p.v(d,G),p.v(d,q),p.v(d,A),p.v(d,E),d.napt=O,d.dvp_log=b,d.napr=Q}d.evid=a;d.ctime=this.hc();return d};this.qe=function(){p.a("ie17");for(var f=[],g=0;g<a.mb;g++)f[g]=d[g]?d[g]:0;return f};var V=this.Kc=function(){return 2==(D&2)&&8!=(P&8)||4==(D&4)||8==(F&8)&&8==(P&8)?!1:!0};this.cf=function(a){p.a("l3");
a=p.ea(a);p.a("cm3e");a&&(A.dbg5=a.w,A.dbg6=a.h);p.a("l3e")};return this}function T(b,c){var e=new S,l=b&&b.impressionId||window.$uid;this.ba=function(b,n){if(c){var h=c.Be(b);n&&e.v(h,n);var p=!1;if(4==b||8==b)p=!0;this.nd(l,h,p)}};this.nd=function(b,c,e){$dv&&$dv.registerEventCall&&b&&$dv.registerEventCall(b,c,null,null,e)}}function U(){this.ba=function(){};this.nd=function(){}}
function X(b,c,e,l){function m(){if(1==u){try{for(var a in q)v.removeChild(q[a]);k.document.body.removeChild(v)}catch(f){}u=!1}}function n(a){a=a||0;var f=r(0);f.dd()?7<f.sb()?(m(),L=B=u=!1):(u=!0,B=!1):20>a?(a++,setTimeout(n,50,a)):(u=B=L=!1,m())}function h(a){$dv&&$dv.tags&&$dv.tags[l]&&$dv.tags[l].getTimeDiff&&$dv.tags[l].getTimeDiff();if(null!==a.kb)for(var f=0;f<a.kb.length;f++){var d=r(f).sb();0==f?d>w&&(w=d):d>E&&(E=d)}}function p(a){for(var f=!0,d=0;13>=d;d++)var g=r(d),f=f&(null!==g&&g.dd());
if(!f)return null;a.Gc=0;a.rc=0;a.qc=0;a.mc=0;a.Ea=0;a.kb=Array(13);f=r(0).sb();for(d=1;13>=d;d++)if(g=5<Math.abs(r(d).sb()-f),a.kb[d]=g)switch(a.Gc++,d){case 2:case 3:case 4:case 5:a.rc++;break;case 6:case 7:case 8:case 9:a.qc++;break;case 10:case 11:case 12:case 13:a.mc++}if(13===a.Gc)return a.Ea=100,h(a),!0;f=a.kb;if(!1===f[1]){if(3<=a.mc||3<=a.qc||3<=a.rc)return h(a),null;a.Ea=0;h(a);return!1}if(!0===f[1]&&(!0===f[2]&&!0===f[3]||!0===f[2]&&!0===f[4]||!0===f[3]&&!0===f[5]||!0===f[4]&&!0===f[5])||
!0===f[1]&&4==a.qc||!0===f[1]&&4==a.mc&&1<=a.rc)return a.Ea=50,h(a),!0;if(f[2]&&f[5]&&!(f[6]&&f[10]&&f[1]&&f[13]&&f[9])||f[4]&&f[3]&&!(f[8]&&f[12]&&f[1]&&f[11]&&f[7]))return h(a),null;a.Ea=0;h(a);return!1}function r(a){a=q[a];var f=null;a&&(f=a.contentWindow);return f}function t(){for(var g=f.getBoundingClientRect(),b=g.width,k=g.height,c=b/(1+a),u=k/(1+a),e=b/a,x=k/a,t=0;13>=t;t++){var h=g.left,v=g.top;switch(t){case 0:v=h=-1E5;break;case 1:h+=(b-d)/2;v+=(k-d)/2;break;case 3:h+=b-d;break;case 4:v+=
k-d;break;case 5:h+=b-d;v+=k-d;break;case 6:h+=(b-e)/2;v+=(k-x)/2;break;case 7:h+=(b-e)/2+e;v+=(k-x)/2;break;case 8:h+=(b-e)/2;v+=(k-x)/2+x;break;case 9:h+=(b-e)/2+e;v+=(k-x)/2+x;break;case 10:h+=(b-c)/2;v+=(k-u)/2;break;case 11:h+=(b-c)/2+c;v+=(k-u)/2;break;case 12:h+=(b-c)/2;v+=(k-u)/2+u;break;case 13:h+=(b-c)/2+c,v+=(k-u)/2+u}6<=t&&(h-=d/2,v-=d/2);var l=q[t];l.style.left=h+"px";l.style.top=v+"px"}}function x(){if(null!=f&&null!=f.parentNode){B=!0;v=k.document.createElement("div");k.document.body.appendChild(v);
for(var a=0;13>=a;a++){var g=k.document.createElement("iframe");g.width=d;g.height=d;g.style.position="absolute";g.frameBorder="0";g.style.visibility="hidden";g.style.zIndex=-9999999;g.style.display="block";g.src="javascript:no=false;yes=true;("+function(){window.We={ae:100};window.Nc=no;window.ib=0;window.Oc=0;window.Yc=0;window.Qf=no;window.sb=function(){return window.Yc};window.dd=function(){return window.Nc};window.Ue=window.requestAnimationFrame||window.mozRequestAnimationFrame||window.webkitRequestAnimationFrame||
window.msRequestAnimationFrame;window.Zb=function(){window.ib++;window.Ue(window.Zb,document)};window.Zb();setInterval(function(){10>window.ib&&window.Zb();window.Yc=window.ib-window.Oc;window.Oc=window.ib},window.We.ae);window.setTimeout(function(){window.Nc=yes},250)}.toString()+")();";v.appendChild(g);q.push(g)}t()}}var a=Math.sqrt(2),d=1,g=new S,k=null,f=null,q=[],v,u=!1,B=!1,L=g.zb(b,c,e);0==g.$a()&&(d=8);var w=0,E=0;this.Ke=function(){0==B&&(0==(this.ab()&&(null!=f&&g.cd(f,k)?!0:!1))?u=!1:(x(),
n()))};this.ab=function(){return L};this.Re=function(){return u};this.ud=function(a,d){k=a;f=d;this.Ke()};this.Ge=function(){if(0==u)return null;var a={};return null==p(a)?null:a.Ea}}
function aa(b,c,e,l,m,n,h,p){this.b=new S;this.window=b;this.c=c;this.S=e;this.O=l;this.Z=h&&h.Enums.BrowserId||window.$dv.Enums.BrowserId;this.aa=h&&h.Enums.TrafficScenario||window.$dv.Enums.TrafficScenario;this.P=m;this.lc=n;this.ia=null;this.Xc=this.window?this.b.Ab(this.window.top):this.b.Ab(window.top);this.Ne=this.S!=this.aa.CrossDomain&&this.b.Wa("ofs")&&this.Xc;this.ia=new X(this.S,this.O,h,p);null!=this.ia&&this.ia.ab()&&this.ia.ud(this.window,this.c);this.vb=this.Cb=this.sa=null;this.wb=
!1;var r=0;this.ja={Qd:1,Rd:2,Kd:4,Rb:8,Jd:16,Sb:32,Pd:64};this.sc=function(b,c,a,d){if(d&&d.insertBefore&&d.firstChild&&(b=this.window.document.createElement(b))){for(var g in c)b[g]=c[g];for(g in a)b.style[g]=a[g];d.insertBefore(b,d.firstChild);return b}return null};this.oe=function(b,c,a){var d=this.window.top,g=b.width,k=b.height;0>a.left?(g=b.width-Math.abs(a.left),0>c.Ca&&(g-=Math.abs(c.Ca))):0>c.Ca&&(g=b.width-Math.abs(c.Ca)+a.left,g=g>b.width?b.width:g);var f=b.width,q=Math.min(this.b.Aa(d.window).clientWidth,
d.innerWidth),h=screen.availWidth-q-c.Ca,u=0;g<f?(f=g,u=q-g,0>c.Ca&&(u-=Math.abs(c.Ca))):u=q-f-a.left;0>u?(g=f-Math.abs(u),0>h&&(g-=Math.abs(h))):0>h&&(g=f-Math.abs(h)+u,g=g>f?f:g);c=screen.availHeight-c.hf-d.outerHeight;d=Math.min(this.b.Aa(d.window).clientHeight,d.innerHeight)-b.height-a.top;0>d?(k=b.height-Math.abs(d),0>c&&(k-=Math.abs(c))):0>c&&(k=b.height-Math.abs(c)+d,k=k>b.height?b.height:k);0>a.top&&(k-=Math.abs(a.top));return{Af:g,Bf:k}};this.gc=function(b,c,a,d){var g=a.C,k=a.B,f=0;a=0;
var q={width:c.right-c.left,height:c.bottom-c.top};if(0>c.bottom||0>c.right||c.top>k||c.left>g||0>=q.width||0>=q.height)return 0;0>c.top?Math.abs(c.top)>=q.height?f=q.height:(f=q.height+c.top,f>k&&(f=k)):f=c.top+q.height>k?k-c.top:q.height;0>c.left?Math.abs(c.left)>=q.width?a=q.width:(a=q.width+c.left,a>g&&(a=g)):a=c.left+q.width>g?g-c.left:q.width;this.Ne&&(b=this.oe(q,b,c),a=b.Af,f=b.Bf);return 0>=a||0>=f?0:Math.round(a*f/(q.width*q.height)*(d?q.width*q.height/((d.right-d.left)*(d.bottom-d.top)):
1)*100)};this.fc=function(b,c){try{var a={x:b.offsetLeft,y:b.offsetTop};if(b.offsetParent){var d=this.fc(b.offsetParent,c);a.x+=d.x;a.y+=d.y}else c!=c.parent&&this.b.Tb(c,c.parent)&&(d=this.fc(c.frameElement,c.parent),a.x+=d.x,a.y+=d.y);return a}catch(g){return{x:null,y:null}}};this.oa=function(b){if(this.S==this.aa.CrossDomain)if(this.b.va(this.window)&&this.window.$sf.ext.geom)this.oa=function(){var a=this.b.Na(this.window),f=window.outerHeight||this.window.document.documentElement.clientHeight?
this.window.outerHeight-parseInt(a.win.h):this.P.Explorer.X,d={C:null,B:null,J:null,K:null,j:!1};d.C=parseInt(a.win.w);d.B=parseInt(a.win.h);d.J=parseInt(a.win.l);d.K=parseInt(a.win.t)+f;d.j=!0;return d};else if(this.O.Y==this.Z.Firefox)this.oa=function(){var a=8==screen.top-this.window.screenY&&8==screen.left-this.window.screenX,f=a?0:this.window.screenX-screen.left,a=a?0:this.window.screenY-screen.top,d={C:null,B:null,J:null,K:null,j:!1};d.C=this.window.outerWidth;d.B=this.window.outerHeight-this.P.Firefox.X;
d.J=f;d.K=a+this.P.Firefox.X;d.j=!0;return d};else if(this.b.nc(this.window)){var c=this;this.window.context.observeIntersection(function(a){a.forEach(function(a){c.sa=a})});this.oa=function(){var a={C:null,B:null,j:!1,J:null,K:null};null!=this.sa?(a.C=this.sa.rootBounds.width,a.B=this.sa.rootBounds.height):(a.C=0,a.B=0);a.j=!0;return a}}else if(this.O.Y==this.Z.IE&&/^[11|12]/.test(this.O.ua))this.oa=function(){var a=-8==this.window.screenY&&-8==this.window.screenX,f=a?0:this.window.screenX,a=a?0:
this.window.screenY,d={C:null,B:null,J:null,K:null,j:!1};d.C=this.window.outerWidth;d.B=this.window.outerHeight-this.P.Explorer.X;d.J=f;d.K=a+this.P.Explorer.X;d.j=!0;return d};else if(this.O.Y==this.Z.IE&&/[6-9]|[10]/.test(this.O.ua)){var a=this.sc("iframe",{name:"dv_ie9onload",src:"",width:0,height:0,je:0,Xe:"0",Ye:"0"},{display:"inline",position:"absolute",top:0,left:0,zf:"none",zIndex:0,border:0},this.window.document.body),d=this.sc("iframe",{name:"dv_ie9onmousemove",src:"",width:0,height:0,je:0,
Xe:"0",Ye:"0"},{display:"inline",position:"absolute",top:0,left:0,zf:"none",zIndex:0,border:0},this.window.document.body),g=d.contentWindow||d.window||d.contentDocument.window||d.contentWindow.window||this.window.Ef,k=a.contentDocument||a.contentWindow.document,a=d.contentDocument||d.contentWindow.document,f="<html><head><script >window.onload = "+function(a){a&&(window.event=a);isFinite(String(window.event.clientY))&&(parent.Va={Wb:window.event.clientY,Vb:window.event.clientX,Cd:window.event.screenY-
window.event.clientY-window.screenY})}.toString()+"; \x3c/script></head><body></body></html>",d='<html><head></head><body><script > function runMoM(){ window.document.body.fireEvent("onmousemove");} window.document.body.onmousemove = '+function(a){a&&(window.event=a);isFinite(String(window.event.clientY))&&(parent.ta={Wb:window.event.clientY,Vb:window.event.clientX,Ia:window.event.screenY-window.event.y,Ha:window.event.screenX-window.event.x})}.toString()+"; runMoM();\x3c/script></body></html>";a.open("text/html",
"replace");a.write(d);a.close();k.open("text/html","replace");k.write(f);k.close();("CSS1Compat"===document.compatMode?this.window.document.documentElement:this.window.document.body).clientLeft;this.oa=function(){g.runMoM();k.open("text/html","replace");k.write(f);k.close();var a=this.window.ta,d=this.window.Va,b=screen.availWidth,c=screen.availHeight,d=d?d.Cd:this.P.Explorer.X;if(a){var h=a.Ha,e=a.Ia;a.Ha>=b&&(a.Ha-=b);a.Ia>=c&&(a.Ia-=c);var t={C:null,B:null,J:null,K:null,j:!1};t.C=this.window.outerWidth?
this.window.outerWidth-20:b-a.Ha-20;t.B=this.window.outerHeight?this.window.outerHeight-d-10:c-a.Ia-10;t.J=h;t.K=e;t.j=!0}else t={C:null,B:null,J:null,K:null,j:!1},t.C=this.window.outerWidth?this.window.outerWidth-20:b-20,t.B=this.window.outerHeight?this.window.outerHeight-d-10:c-10,t.J=null,t.K=null,t.j=!1;return t}}else this.b.yb()?(this.ld(),this.oa=function(){this.wb||this.ld();var a={C:null,B:null,J:null,K:null,j:!1};a.C=this.window.outerWidth;a.B=this.window.outerHeight-this.P.Chrome.X;a.j=
!1;return a}):this.oa=this.O.Y==this.Z.Chrome?function(){var a={C:null,B:null,J:null,K:null,j:!1},f=!1;try{a.C=this.window.frameElement.offsetParent.parentNode.clientWidth,a.B=this.window.frameElement.offsetParent.parentNode.clientHeight,f=!0}catch(d){}a.J=this.window.screenX;a.K=this.window.screenY;a.j=f;return a}:null!=this.ia&&this.ia.ab()?function(){var a={C:null,B:null,J:null,K:null,j:!1};a.C=this.window.outerWidth;a.B=this.window.outerHeight-this.P.Safari.X;a.j=!1;return a}:function(){return{C:null,
B:null,J:null,K:null,j:!1}};else this.oa=function(){var a,f,d=this.window.top;void 0!=d.mozInnerScreenX&&null!=d.mozInnerScreenX?(a=d.mozInnerScreenX,f=d.mozInnerScreenY):void 0!=d.screenX&&null!=d.screenX?0!=d.screenLeft+8&&d.screenLeft+8!=screen.width||0!=d.screenTop+8&&d.screenTop+8!=screen.height?(a=d.screenLeft,f=d.screenTop+(d.outerHeight-d.innerHeight)):(a=d.screenLeft+8,f=d.screenTop+(d.outerHeight-d.innerHeight)+8):(a=d.screenLeft,f=d.screenTop);var g={C:null,B:null,J:null,K:null,j:!1},b=
this.b.Aa(d);g.C=d.innerWidth||b.clientWidth;g.B=d.innerHeight||b.clientHeight;g.J=a;g.K=f;g.j=!0;return g};return this.oa(b)};this.ma=function(b,c){r=1;this.S==this.aa.CrossDomain?this.b.va(this.window)&&this.window.$sf.ext.geom&&this.b.Na(this.window).par?(r=8,this.ma=function(){var a=this.b.Na(this.window),d=window.outerHeight||this.window.document.documentElement.clientHeight?this.window.outerHeight-parseInt(a.win.h):this.P.Explorer.X,g={u:null,s:null,L:null,M:null,F:null,G:null,o:null,m:null,
j:!1,rect:null,R:null,ra:null};g.u=parseInt(a.self.l)-parseInt(a.par.l);g.s=parseInt(a.self.t)-parseInt(a.par.t);g.L=parseInt(a.self.l);g.M=parseInt(a.self.t);g.F=parseInt(a.win.l)+g.u;g.G=parseInt(a.win.t)+g.s+d;g.o=parseInt(a.self.w);g.m=parseInt(a.self.h);g.j=!0;g.rect={top:g.s,bottom:g.s+g.m,left:g.u,right:g.u+g.o};return g}):this.O.Y==this.Z.Firefox?this.ma=function(){var a=1;window.devicePixelRatio&&(a=window.devicePixelRatio);var d=this.window.screenX,g=this.window.screenY,b=this.window.mozInnerScreenX/
a-d,a=this.window.mozInnerScreenY/a-g-this.P.Firefox.X,b={left:b,top:a,right:b+this.window.innerWidth,bottom:a+this.window.innerHeight},a={u:null,s:null,L:null,M:null,F:null,G:null,o:null,m:null,j:!1,rect:null,R:null,ra:null};a.u=b.left;a.s=b.top;a.L=null;a.M=null;a.F=d+b.left;a.G=g+b.top;a.o=this.window.innerWidth;a.m=this.window.innerHeight;a.j=!0;a.rect=b;this.b.Lb()&&(a=this.qb(a));return a}:this.b.nc(this.window)?(r=32,this.ma=function(){var a={u:null,s:null,o:null,m:null,j:!1,rect:null,R:null,
ra:null,L:null,M:null,F:null,G:null};null!=this.sa?(a.u=this.sa.boundingClientRect.left,a.s=this.sa.boundingClientRect.top,a.o=this.sa.boundingClientRect.width,a.m=this.sa.boundingClientRect.height):(a.u=0,a.s=0,a.o=0,a.m=0);a.j=!0;a.rect={top:a.s,bottom:a.s+a.m,left:a.u,right:a.u+a.o};return a}):this.O.Y==this.Z.IE&&/^[11|12]/.test(this.O.ua)?this.ma=function(a){var d=this.window.screenLeft-window.screenX,g=this.window.screenTop-window.screenY-this.P.Explorer.X,d={left:d,top:g,right:d+this.window.innerWidth,
bottom:g+this.window.innerHeight},g={u:null,s:null,L:null,M:null,F:null,G:null,o:null,m:null,j:!1,rect:null,R:null,ra:null};g.u=d.left;g.s=d.top;g.L=null;g.M=null;g.F=a.J+d.left;g.G=a.K+d.top;g.o=this.window.innerWidth;g.m=this.window.innerHeight;g.j=!0;g.rect=d;this.b.Lb()&&(g=this.qb(g));return g}:this.O.Y==this.Z.IE&&/[6-9]|[10]/.test(this.O.ua)?this.ma=function(){if(8==document.documentMode)return{u:null,s:null,L:null,M:null,F:null,G:null,o:null,m:null,j:!1,rect:null,R:null,ra:null};var a=this.window.Va&&
this.window.ta?this.window.Va.Wb-this.window.ta.Wb:0,d=this.window.Va&&this.window.ta?this.window.Va.Vb-this.window.ta.Vb:0,g=this.b.Aa(this.window),b={u:null,s:null,L:null,M:null,F:null,G:null,o:null,m:null,j:!1,rect:null,R:null,ra:null};b.u=d;b.s=a;b.L=null;b.M=null;b.F=this.window.ta?d+this.window.ta.Ha:null;b.G=this.window.ta?a+this.window.ta.Ia:null;b.o=this.window.innerWidth||g.clientWidth;b.m=this.window.innerHeight||g.clientHeight;b.j=!0;b.rect={left:d,top:a,right:d+(this.window.innerWidth||
g.clientWidth),bottom:a+(this.window.innerHeight||g.clientHeight)};this.b.Lb()&&(b=this.qb(b));return b}:this.b.yb()?(r=512,this.ma=function(){var a={u:null,s:null,L:null,M:null,F:null,G:null,o:null,m:null,j:!1,rect:null,R:null,ra:null};null!=this.c&&(adData=this.b.rb(this.c),a.o=adData?adData.w:this.window.innerWidth,a.m=adData?adData.h:this.window.innerHeight);return a}):this.ma=this.O.Y==this.Z.Chrome?function(){var a=null,d=null,b=!1;try{var c=this.window.frameElement.offsetTop,a=this.window.frameElement.offsetLeft-
this.window.frameElement.offsetParent.scrollLeft,d=c-this.window.frameElement.offsetParent.scrollTop,b=!0}catch(f){}c={u:null,s:null,L:null,M:null,F:null,G:null,o:null,m:null,j:!1,rect:null,R:null,ra:null};c.u=a;c.s=d;c.L=null;c.M=null;c.F=null;c.G=null;c.o=this.window.innerWidth;c.m=this.window.innerHeight;c.j=b;c.rect=b?{left:a,top:d,right:a+this.window.innerWidth,bottom:d+this.window.innerHeight}:null;this.b.Lb()&&(c=this.qb(c));return c}:null!=this.ia&&this.ia.ab()?function(){var a={u:null,s:null,
L:null,M:null,F:null,G:null,o:null,m:null,j:!1,rect:null,R:null,ra:null};null!=this.c&&(adData=this.b.rb(this.c),a.o=adData?adData.w:this.window.innerWidth,a.m=adData?adData.h:this.window.innerHeight);return a}:function(){return{u:null,s:null,L:null,M:null,F:null,G:null,o:null,m:null,j:!1,rect:null,R:null,ra:null}}:this.ma=function(a){var d=this.fc(this.c,this.window),b={u:null,s:null,L:null,M:null,F:null,G:null,o:null,m:null,j:!1,rect:null,R:null,ra:null},c=this.b.ic(this.c,this.window),f=this.b.zc(this.c,
this.window);b.u=f.left;b.s=f.top;b.L=d.x;b.M=d.y;b.F=a.J+f.left;b.G=a.K+f.top;b.o=f.w;b.m=f.h;b.j=!0;b.rect=c;b.R=f;return b};return this.ma(b,c)};this.qb=function(b){if(this.window.document.body==this.c||this.window.document.documentElement==this.c)return b;var c=this.b.rb(this.c);if(c){var a=c.w,d=c.h,g=b.u,k=b.s,f=b.G,q=b.F;null!=b.u&&null!=b.s&&null!=b.m&&null!=b.o&&b.rect&&(0<c.t?(k=b.s+c.t,null!=b.G&&(f=b.G+c.t)):d+=c.t,0<c.l?(g+=c.l,null!=b.F&&(q=b.F+c.l)):a+=c.l,c.r>b.o&&(a-=c.r-b.o),c.Fc>
b.m&&(d-=c.Fc-b.m),b.o=0<a?a:0,b.m=0<d?d:0,b.u=g,b.s=k,b.G=f,b.F=q,b.rect.left=b.u,b.rect.top=b.s,b.rect.right=b.u+c.w,b.rect.bottom=b.s+c.h,b.R={w:a,h:d,left:g,right:g+a,top:k,bottom:k+d})}return b};this.Ce=function(){var b=screen.availWidth,c=screen.availHeight,a=screen.width,d=screen.height,g=0,k=0;this.Xc&&(k=this.window.top,g=k.screenX,k=k.screenY);return{j:this.P.$a?!1:"undefined"!==typeof g,Fb:b||a,Eb:c||d,Nf:g,Of:k,Ca:g-(a-b),hf:k-(d-c)}};this.me=function(){var b=this.Ce(),c=this.oa(b),a=
this.ma(c,b);return{ga:c,i:a,xa:b,Mb:(null==c.J||null==c.K?0:this.ja.Qd)|(null==c.C||null==c.B?0:this.ja.Rd)|(null==a.u||null==a.s?0:this.ja.Kd)|(null==a.L||null==a.M?0:this.ja.Rb)|(null==a.F||null==a.G?0:this.ja.Jd)|(null==a.m||null==a.o?0:this.ja.Sb)|(null==b.Eb||null==b.Fb?0:this.ja.Pd),N:this.$b(a.m,a.o)}};this.$b=function(b,c,a){null==b&&(b=0);null==c&&(c=0);return 1!=this.P.$a||a?242500<=b*c:!1};this.ue=function(){this.b.a("c10");if(null!=this.c)if(this.b.cd(this.c,this.window))try{var b={timeStamp:new Date,
g:-3,ka:-3,A:null,N:!1,ha:0};if(!this.lc())return b;var c=this.me();if(!c.i.j||!c.ga.j){if(this.b.va(this.window)&&this.window.$sf.ext.inViewPercentage){var a=this.window.$sf.ext.inViewPercentage();return{timeStamp:new Date,g:a,ka:a,A:c,N:c.N,ha:16}}if(this.b.yb()&&this.wb)return a=0,null!=this.vb&&(a=Math.round(100*this.vb.intersectionRatio)),{timeStamp:new Date,g:a,ka:a,A:c,N:this.$b(c.i.m,c.i.o),ha:512};if(this.ia.ab()){var d={timeStamp:new Date,g:-3,ka:-3,A:null,N:!1,ha:2};if(0==this.ia.Re())d.g=
-6,d.ka=-6,this.ia.ud(this.window,this.c);else{var g=this.ia.Ge();null!=g&&(d.A=c,d.N=c.N,d.g=g,d.ka=g)}return d}b.A=c;r&&(b.ha=r);return b}if(c.i&&c.i.R&&(0===c.i.R.w||1===c.i.R.w||0===c.i.R.h||1===c.i.R.h))return{timeStamp:new Date,g:-5,ka:-5,A:c,ha:r};a=c.i.R?this.gc(c.xa,c.i.R,c.ga,c.i.rect):this.gc(c.xa,c.i.rect,c.ga);return{timeStamp:new Date,g:a,ka:a,A:c,N:c.N,ha:r}}catch(k){return{timeStamp:new Date,g:-4,ka:-4,A:null,N:!1,ha:r}}else return{timeStamp:new Date,g:-2,ka:-2,A:null,N:!1,ha:0};else return{timeStamp:new Date,
g:-1,ka:-1,A:null,N:!1,ha:0}};this.ne=function(b,c){this.b.a("c11");var a=null,d=null;if(null!=b.A){var g=b.A.i;c<=this.P.$e&&(a=0<=b.g||-5==b.g?b.N&&b.g>=this.P.bb||0==b.N&&50<=b.g?!0:!1:null,d=b.N?this.P.bb/100:.5,d=0==a?0>g.s+g.m*d?!0:!1:1==a?!1:null)}return{Zc:d,$c:a}};this.xb=function(b){this.b.a("c12");var c=null;if(2!=b.ha&&512!=b.ha&&null!=b.A){var a=b.A.Mb,d=b.A.i;(a&this.ja.Rb)==this.ja.Rb&&(a&this.ja.Sb)==this.ja.Sb&&(c=this.gc(b.A.xa,{left:d.L,top:d.M,right:d.L+d.o,bottom:d.M+d.m},b.A.ga,
d.rect),c=0<=b.g?b.N&&c>=this.P.bb||0==b.N&&50<=c?!1:!0:null)}this.b.a("c12e");return c};this.ld=function(){function b(a){a.forEach(function(a){c.vb=a})}var c=this;"undefined"!=typeof IntersectionObserver&&null!=this.c&&(r=512,this.Cb=new IntersectionObserver(b,{threshold:[0,.1,.2,.3,.4,.5,.6,.7,.8,.9,1]}),this.Cb.observe(this.c),this.wb=!0)};this.Je=function(){this.c=null;null!=this.Cb&&(this.Cb.disconnect(),this.vb=null,this.wb=!1)}}
function S(){this.getElementVolume_object=function(b){var c=b.getAttribute("width"),e=b.getAttribute("height");null==c||""==c||null==e||""==e?(b=b.parentNode,b={w:b.clientWidth,h:b.clientHeight}):b={w:c,h:e};return b};this.Se=function(b){var c=0;try{for(;null!=b&&10>c;){if("none"==window.getComputedStyle(b).display||"hidden"==window.getComputedStyle(b).visibility)return!1;b=b.parentElement;c++}}catch(e){}return!0};this.ea=function(b,c){this.a("cm1");var e=null,l=b.nodeName.toLowerCase();c&&this["getElementVolume_"+
l]&&(e=this["getElementVolume_"+l](b));if(!e&&(e=this.rb(b),this.a("cm2e"),!e||1>=e.w||1>=e.h))return this.a("cm1e"),{w:0,h:0};e.w.indexOf&&e.w.indexOf("px")&&(e.w=e.w.replace("px",""));e.h.indexOf&&e.h.indexOf("px")&&(e.h=e.h.replace("px",""));this.a("cm1e");return e};this.rb=function(b){this.a("cm2");try{var c;return document.body.getBoundingClientRect&&(c=b.getBoundingClientRect())?{w:c.right-c.left,h:c.bottom-c.top,l:c.left,t:c.top,Fc:c.bottom,r:c.right}:null}catch(e){return null}};this.Aa=function(b){this.a("ff8");
b=b.document.documentElement.clientHeight?b.document.documentElement:b.document.body;this.a("ff8e");return b};this.Rc=function(b,c){this.a("ff9");var e=0,l=!1;if(b.document.all)for(var m=0;m<b.document.all.length;m++)"BODY"==b.document.all[m].nodeName&&(l=!0),l&&("width"==c?b.document.all[m].width>e&&(e=b.document.all[m].width):b.document.all[m].height>e&&(e=b.document.all[m].height));this.a("ff9e");return e};this.fd=function(b,c){for(var e=this.Aa(b),l=b.innerWidth||e.clientWidth||this.Rc(b,"width"),
e=b.innerHeight||e.clientHeight||this.Rc(b,"height"),m=c.length,n=0,h=0;h<m;h++)if(15>=Math.abs(l-c[h].w)){n=c[h].h.length;for(l=0;l<n;l++)if(15>=Math.abs(e-c[h].h[l]))return!0;break}return!1};this.wf=function(b){for(var c=[],e=-1;c[++e]=b[e];);c.length--;return c};this.Ob=function(b,c,e,l){var m=b.getElementsByTagName("*"),m=this.wf(m);m.unshift(b);for(var n=["EMBED","IFRAME","OBJECT","IMG","DIV"],h=[],p=0;p<m.length;p++){var r=m[p];if(-1!=n.indexOf(r.nodeName)){var t=l(r);t&&h.push({Ec:t.w*t.h,
w:t.w,h:t.h,type:r.nodeName||"other",ie:r})}}h=h.sort(function(b,a){return a.Ec-b.Ec||n.indexOf(a.type)-n.indexOf(b.type)});(c=0<h.length&&h[0].w>c&&h[0].h>e?h[0].ie:null)&&b&&(c.ub=b.ub);return c};this.cd=function(b,c){this.a("ff10");try{if(!b)return!1;for(c||(c=window);b!=c.document&&b.parentNode;)b=b.parentNode;this.a("ff10e");return b==c.document}catch(e){return!1}};this.ic=function(b,c){var e=c.parent,l={left:0,right:0,top:0,bottom:0};if(b){var m=b.getBoundingClientRect();c!=e&&this.Tb(c,e)&&
(l=this.ic(c.frameElement,e));l={left:m.left+l.left,right:m.right+l.left,top:m.top+l.top,bottom:m.bottom+l.top}}return l};this.Tb=function(b,c){var e=!1;if(b==c)e=!0;else try{b.document.domain==c.document.domain&&(e=!0)}catch(l){}return e};this.ve=function(b){if(b)try{if(b.contentDocument&&this.bd(b.contentDocument))return b.contentDocument;if(b.contentWindow&&this.Ab(b.contentWindow))return b.contentWindow.document}catch(c){}return null};this.Vc=function(b){return b?b.defaultView||b.parentWindow:
null};this.Me=function(b,c){return-1<c.indexOf(b)};this.pe=function(b){try{return b!=b.top&&b.parent&&this.Ab(b.parent)?b.parent:null}catch(c){return null}};this.Ab=function(b){try{return b&&b.document&&this.bd(b.document)?!0:!1}catch(c){return!1}};this.bd=function(b){try{return b&&b.getElementsByTagName&&b.getElementById?!0:!1}catch(c){return!1}};this.zc=function(b,c){var e=c.parent,l={w:0,h:0,left:0,right:0,top:0,bottom:0};b&&(l=this.ic(b,c),l.w=l.right-l.left,l.h=l.bottom-l.top,c!=e&&this.Tb(c,
e)&&(e=this.zc(c.frameElement,e),e.bottom<l.bottom&&(e.bottom<l.top&&(l.top=e.bottom),l.bottom=e.bottom),e.top>l.top&&(e.top>l.bottom&&(l.bottom=e.top),l.top=e.top),e.right<l.right&&(e.right<l.left&&(l.left=e.right),l.right=e.right),e.left>l.left&&(e.left>l.right&&(l.right=e.left),l.left=e.left),l.w=l.right-l.left,l.h=l.bottom-l.top));return l};this.ac=function(b,c){return function(){return b.apply(c,arguments)}};this.na=function(b){try{return b?b.length?b.length:0:0}catch(c){return 0}};this.kc=function(b){for(var c=
[],e=0;e<b.length;e++)this.Se(b[e])&&c.push(b[e]);return c};this.a=function(b){try{maxLength=3,$dv&&($dv.Oa=$dv.Oa||[],$dv.Oa.push(b),$dv.Oa.length>maxLength&&$dv.Oa.shift())}catch(c){}};this.ye=function(){try{return $dv&&$dv.Oa?$dv.Oa.join():""}catch(b){return""}};this.va=function(b){if(b.$sf&&b.$sf.ext)if(b.$sf.ext.geom){if(b=this.Na(b),null!=b&&b.win&&(0<b.win.h||0<b.win.w))return this.va=function(){return!0},!0}else if(b.$sf.ext.inViewPercentage)return!0;this.va=function(){return!1};return!1};
this.Na=function(b){b.$sf.ext.geom&&(this.Na="function"==typeof b.$sf.ext.geom?function(b){return b.$sf.ext.geom()}:function(b){return b.$sf.ext.geom});return this.Na(b)};this.v=function(b,c){if(null!=b&&null!=c)for(var e in c)c.hasOwnProperty(e)&&(b[e]=c[e])};this.nc=function(b){return b.context&&b.context.observeIntersection?!0:!1};this.yb=function(){var b=!1;if(1==this.Wa("disableIO"))return!1;"undefined"!=typeof IntersectionObserver&&(b=!0);return b};this.zb=function(b,c,e){var l=e&&e.Enums.BrowserId||
window.$dv.Enums.BrowserId;if(b==(e&&e.Enums.TrafficScenario||window.$dv.Enums.TrafficScenario).CrossDomain&&c.Y===l.Safari&&(null===c.ua||void 0===c.ua||!/^[3-8]/.test(c.ua)))return this.zb=function(){return!0},!0;this.zb=function(){return!1};return!1};this.Wa=function(b){var c,e=this.Pc();e&&e.AVO&&(c=e.AVO[b]);return c};this.Pc=function(){var b={},c=window.$dv,e=window.$uid;c.tags&&c.tags[e]&&(b=c.tags[e]);return b};this.Lb=function(){return 1==this.Wa("sam")?!0:!1};this.Ya=function(b){return b.document.hasFocus()};
this.Ma=new function(){var b=this;b.cache=[];window.addEventListener?b.add=function(c,e,l,m,n){if("undefined"==typeof m||null==m)m=window;m.addEventListener(c,e,l);n&&b.cache.push([c,e,l,m])}:window.attachEvent?b.add=function(c,e,l,m,n){if("undefined"==typeof m||null==m)m=window;m["e"+c+e]=e;m[c+e]=function(){m["e"+c+e](window.event)};m.attachEvent("on"+c,m[c+e]);n&&b.cache.push([c,e,l,m])}:b.add=function(){};window.removeEventListener?b.remove=function(b,e,l,m){if("undefined"==typeof m||null==m)m=
window;m.removeEventListener(b,e,l)}:window.detachEvent?b.remove=function(b,e,l,m){if("undefined"==typeof m||null==m)m=window;m.detachEvent("on"+b,m[b+e]);m[b+e]=null;m["e"+b+e]=null}:b.remove=function(){};b.flush=function(){for(var c=0;c<b.cache.length;c++)b.remove.apply(b,b.cache[c]);b.cache=[]}};this.getElementsByClassName=function(b,c){return b.getElementsByClassName?b.getElementsByClassName(c):b.querySelectorAll?b.querySelectorAll("."+c):[]};this.$a=function(){var b=!1;if($dv&&$dv.CommonData){var c=
$dv.CommonData.detectedDeliveryType;c&&0!=c?b=2==c||3==c:(c=$dv.CommonData.deviceType)&&(b=2==c||3==c)}return b};this.xe=function(b,c){var e=b||"",l="";if(c&&(e+=": "+(c.message||""),c.stack)){var l=c.stack||"",m=l.indexOf("at ");0>m&&(m=0);l=", Stack: "+l.slice(m,l.length)}e=e.replace(/\n/g,"").replace(/\r/g,"").replace(/\t/g,"").replace(/\|/g,"");l=l.replace(/\n/g,"").replace(/\r/g,"").replace(/\t/g,"").replace(/\|/g,"").replace(/    at/g,"at").replace(/\?/g,"-").replace(/&/g,"-");m=null;try{m=
encodeURIComponent(e+l).slice(0,500)}catch(n){try{m=encodeURIComponent(e).slice(0,500)}catch(h){m=e.slice(0,500)}}return m}}
function ba(b,c,e,l,m){function n(a,b){for(var g=[],c=0;c<r.length;c++){var f=[],f=b(a,r[c]),q=h.na(f);if(0!=q){var e=h.Vc(r[c]);if(null!=e)for(var u=0;u<q;u++)try{f[u].ub=e,g.push(f[u])}catch(l){}}}return g}var h=new S,p="Microsoft Internet Explorer"==navigator.appName;this.f=l;this.window=e;this.Nb=[["DCF",'"'],[";",";"],["%3B","%3B"],["zoneid=","_"],["zoneid%3D","_"],["PRImpID=",""],["PRImpID%3D",""],["PRPID=",""],["PRPID%3D",""]];this.Db=[1==p?"object":"embed",1==p?"embed":"object","href","img",
"span","iframe","frameElement","div"];this.Jb=this.c=null;this.dataObj=b;this.dvObj=b.dvObj||window.$dv;this.O={Y:this.dvObj.CommonData.BrowserId,ua:this.dvObj.CommonData.BrowserVersion};this.Z=this.dvObj.Enums.BrowserId;this.S=m;this.aa=this.dvObj.Enums.TrafficScenario;this.de=function(){var a=this.dataObj.ob+"-"+this.dataObj.nb;this.dataObj.isBrandShieldOrigin&&(a+="-bs");return a.replace(RegExp(",","g"),";")};this.uc=this.de();this.V=c;this.D={H:{h:1,w:1},Cf:{h:10,w:10},Ze:10};115==this.dataObj.Xb&&
(this.D.H.h=20,this.D.H.w=20);this.dataObj.findclass&&1==this.dataObj.findclass&&this.Db.push("classDeclaration");this.dataObj.lb&&0<this.dataObj.lb.length&&this.Db.unshift("searchCustomElementsFromTag");this.searchByAdSrvId_8=function(a,b){h.a("a1");var g=/[0-9]+-[0-9]+-[0-9]+-[0-9]+/.exec(a);return null!=g&&(g=g.toString(),g.replace(RegExp("-","g"),"")==b)?!0:!1};this.bc=this["searchByAdSrvId_"+(this.dataObj?this.dataObj.Xb||"":"")];this.getElementsByClassName=function(a,b){return n(a,function(a,
c){h.a("ff1");var f=c.getElementsByClassName(a);h.a("ff1e");return"1"!=b?f:h.kc(f)})};this.querySelectorAll=function(a,b){return n(a,function(a,c){h.a("ff3");var f=c.querySelectorAll("."+a);h.a("ff3e");return"1"!=b?f:h.kc(f)})};this.getElementsByTagName=function(a,b){return n(a,function(a,c){h.a("ff4");var f=c.getElementsByTagName(a);h.a("ff4e");return"1"!=b?f:h.kc(f)})};this.classDeclaration=function(){h.a("a9");var a="undefined"!==typeof window.document.getElementsByClassName,b="undefined"!==typeof window.document.querySelectorAll;
if(!(1>this.dataObj.I.length)){var c=[];if(a)c=this.getElementsByClassName(this.dataObj.I,this.dataObj.displaynon);else if(b)c=this.querySelectorAll(this.dataObj.I,this.dataObj.displaynon);else return;a=h.na(c);for(b=0;b<a;b++)if(c[b]&&!this.qa(c[b])){var k=h.ea(c[b]);if(k&&k.h>this.D.H.h&&k.w>this.D.H.w&&this.T(c[b])){this.c=c[b];break}}}};this.searchCustomElementsFromTag=function(){for(var a=0;a<this.dataObj.lb.length&&(this.Lc(this.dataObj.lb[a]),!this.c);a++);};this.Lc=function(a){if(!(1>this.dataObj.I.length)){a=
this.getElementsByTagName(a,this.dataObj.displaynon);for(var b=h.na(a),c=0;c<b;c++)if(a[c]&&this.ya(this.dataObj,a[c],!0)&&!this.qa(a[c])){var k=h.ea(a[c]);if(k&&k.h>this.D.H.h&&k.w>this.D.H.w&&this.T(a[c])){this.c=a[c];break}var f=h.Ob(a[c],this.D.H.w,this.D.H.h,h.ac(h.ea,h));if(f&&this.T(f)){this.c=f;this.T(a[c]);break}if((f=this.ad(a[c]))&&(k=h.ea(f))&&k.h>this.D.H.h&&k.w>this.D.H.w&&this.T(f)){this.c=f;this.T(a[c]);break}}}};this.div=function(){this.Lc("div")};this.span=function(){h.a("a10");
if(!(1>this.dataObj.I.length))for(var a=this.getElementsByTagName("span",this.dataObj.displaynon),b=h.na(a),c=0;c<b;c++)if(a[c]&&this.ya(this.dataObj,a[c],!0)&&!this.qa(a[c])){if(this.Le(a[c])){this.c=a[c];break}var k=h.Ob(a[c],this.D.H.w,this.D.H.h,h.ac(h.ea,h));if(k&&this.T(k)){this.c=k;this.T(a[c]);break}if(k=this.ad(a[c])){var f=h.ea(k);if(f&&f.h>this.D.H.h&&f.w>this.D.H.w&&this.T(k)){this.c=k;this.T(a[c]);break}}}};this.object=function(){h.a("a11");for(var a=this.getElementsByTagName("object",
this.dataObj.displaynon),b=h.na(a),c=0;c<b;c++)if(a[c]&&this.ya(this.dataObj,a[c])&&!this.qa(a[c])){var k=h.Ob(a[c],this.D.H.w,this.D.H.h,h.ac(h.ea,h));if(k&&this.T(k)){this.T(a[c]);this.c=k;break}}};this.embed=function(){h.a("a12");for(var a=this.getElementsByTagName("embed",this.dataObj.displaynon),b=h.na(a),c=0;c<b;c++)if(a[c]&&this.ya(this.dataObj,a[c])&&!this.qa(a[c])){var k=h.ea(a[c]);if(k&&k.h>this.D.H.h&&k.w>this.D.H.w&&this.T(a[c])){this.c=a[c];break}}};this.href=function(){h.a("a13");for(var a=
this.getElementsByTagName("a",this.dataObj.displaynon),b=h.na(a),c=0;c<b;c++)if(a[c]&&this.ya(this.dataObj,a[c])&&!this.qa(a[c])){var k=a[c].getElementsByTagName("img");if(0<k.length){var f=h.ea(k[0]);if(f&&f.h>this.D.H.h&&f.w>this.D.H.w&&this.T(a[c])){this.c=k[0];break}}}};this.img=function(){h.a("a14");for(var a=this.getElementsByTagName("img",this.dataObj.displaynon),b=h.na(a),c=0;c<b;c++)if(a[c]&&this.ya(this.dataObj,a[c])&&0>a[c].src.indexOf("event")&&!this.qa(a[c])){var k=h.ea(a[c]);if(k&&k.h>
this.D.H.h&&k.w>this.D.H.w&&this.T(a[c])){this.c=a[c];break}}};this.iframe=function(){h.a("a15");for(var a=this.getElementsByTagName("iframe",this.dataObj.displaynon),b=h.na(a),c=0;c<b&&!this.Cc(a[c]);c++);};this.frameElement=function(){try{h.a("a16"),this.S==this.aa.SameDomain&&this.Cc(this.window.frameElement)}catch(a){}};this.Cc=function(a){h.a("a17");return this.ya(this.dataObj,a)?this.Sd(a):!1};this.T=function(a){h.a("a18");if(a&&0==this.qa(a))try{var b=a.getAttribute("dvvisit");b?a.setAttribute("dvvisit",
b+","+this.uc):(h.a("ff5"),b=this.window.document.createAttribute("dvvisit"),h.a("ff5e"),b.value=this.uc,a.setAttributeNode(b));return!0}catch(c){}return!1};this.bf=function(a){a&&a.hasAttribute&&a.hasAttribute("dvvisit")&&a.removeAttribute("dvvisit")};this.ff=function(){this.bf(this.c);this.c=null};this.qa=function(a){h.a("a19");if(a&&(a=a.getAttribute("dvvisit"))){a=a.split(",");for(var b=0;b<a.length;b++)if(a[b]==this.uc)return!0}return!1};this.Le=function(a){h.a("a20");return a&&"1"==a.getAttribute("adunit")?
!0:!1};this.ad=function(a){var b=null;if("celtra-ad-v3"==a.className)this.Za=!0,a.celtra&&1==a.celtra.loaded&&(b=a.celtra.viewabilityObservee);else{a=h.getElementsByClassName(a,"celtra-ad-v3");for(var c=h.na(a),k=0;k<c;k++){this.Za=!0;var f=a[k];if(f&&f.celtra&&1==f.celtra.loaded){b=f.celtra.viewabilityObservee;break}}}b&&(b.ub=h.Vc(b.ownerDocument)||this.window);return b};this.Sd=function(a){h.a("a21");if(a&&!this.qa(a)){var b=h.ea(a);if(b&&b.h>this.D.H.h&&b.w>this.D.H.w&&this.T(a))return this.c=
a,!0}return!1};this.ya=function(a,b,c){h.a("a22");var k=null;return a.I&&0<a.I.length&&(this.Ac=1==a.Te?this.Gd:this.Pb,k=this.Md(a,b,c))||!this.c&&(k=this.Nd(a,b))?!0:!1};this.Md=function(a,b,c){h.a("a23");var k;try{if(a.Jc&&b&&b.hasAttribute&&b.hasAttribute("dv-view"))return!0;(k=this.la(b.id,a.I))||(k=this.la(b.src,a.I));k||(k=this.la(b.href,a.I));k||(k=this.la(b.getAttribute("flashvars"),a.I));k||(k=this.la(b.name,a.I));!k&&this.dataObj.findclass&&1==this.dataObj.findclass&&(k=this.la(b.getAttribute("class"),
a.I));if(!k&&this.dataObj.Ka&&0<this.dataObj.Ka.length)for(var f=this.dataObj.Ka,q=0;q<f.length&&!(k=this.la(b.getAttribute(f[q]),a.I));q++);k||c||(k=this.la(b.innerHTML,a.I));k&&!c&&(k=this.Ld(a,b));return k}catch(e){return k}};this.Nd=function(a,b){h.a("a24");var c;try{if(a.Jc&&b&&b.hasAttribute&&b.hasAttribute("dv-view"))return!0;(c=this.Fa(b.id,a))||(c=this.Fa(b.src,a));c||(c=this.Fa(b.href,a));c||(c=this.Fa(b.Hf,a));c||(c=this.Fa(b.name,a));c||(c=this.Fa(b.innerHTML,a));if(!c&&this.dataObj.Ka&&
0<this.dataObj.Ka.length)for(var k=this.dataObj.Ka,f=0;f<k.length&&!(c=this.la(b.getAttribute(k[f]),a.I));f++);return c}catch(q){return c}};this.Fa=function(a,b){h.a("a25");if(!a)return!1;a=a.toLowerCase();for(var c=0;c<this.Nb.length;c++){var k;if(b.Dc&&(k=(this.Nb[c][0]+b.Dc).toLowerCase(),k=a.indexOf(k),-1<k)||b.hd&&(k=(this.Nb[c][0]+b.hd).toLowerCase(),k=a.indexOf(k),-1<k))return!0}return!1};this.Ld=function(a,b){h.a("a26");return null==a.Ua||""==a.Ua?!1:this.la(this.Fd(b),a.Ua)};this.Fd=function(a){h.a("a27");
if(a.outerHTML)return a.outerHTML;for(var b=a.attributes.length,c="",k=0;k<b;k++)c=c+a.attributes[k].nodeName+"="+a.attributes[k].nodeValue+" ";return c+a.innerHTML};this.la=function(a,b){h.a("a28");return!a||!b||5>b.length?!1:null!=(this.Ac?this.Ac(a,b):this.Pb(a,b))?!0:this.bc&&"function"===typeof this.bc?this.bc(a,b):!1};this.Gd=function(a,b){h.a("a29");var c;try{c=(new RegExp(b)).exec(a)}catch(k){c=this.Pb(a,b)}return c};this.Pb=function(a,b){h.a("a30");var c=null;-1!==a.indexOf(b)&&(c=a);return c};
this.ke=function(a){h.a("a31");if(this.ze())return this.f.Ad(),this.Za||(this.Za=!0),this.c;if(this.dataObj.I&&0<this.dataObj.I.length&&!0===this.Za&&1<a)return this.c;"1"!=this.dataObj.displaynon&&(a=this.Ae())&&a.node&&(this.f.zd(a.La),this.c=a.node);return this.c};var r=[];this.ze=function(){h.a("32");if(this.dataObj.I&&0<this.dataObj.I.length){var a=this.Db.length,b=this.window,c=0,k=[];try{do{k.push(b.document);for(var f=k,q=b.document.getElementsByTagName("iframe")||[],e=0;e<q.length||25>e;e++){var u=
null,u=h.ve(q[e]);void 0!==u&&null!==u&&0==h.Me(u,f)&&f.push(u)}b=h.pe(b)}while(b&&10>++c)}catch(l){}r=k;for(b=0;b<a;b++)if(this[this.Db[b]](),this.c){this.Jb=this.c;break}}return this.c};var t=[],x=["object","embed","img","iframe"];this.dataObj.spotXmode&&(x=["object","embed","video","iframe"]);this.Pe=function(a){h.a("a33");a=h.ea(a);return this.Qe(a)};this.Qe=function(a){if(a){var b=a.w;a=a.h;for(var g=c.length,e=0,f=0;f<g;f++)if(15>=Math.abs(b-c[f].w))for(var e=c[f].h.length,q=0;q<e;q++)if(15>=
Math.abs(a-c[f].h[q]))return!0}return!1};this.se=function(){h.a("a34");return this.te()||this.jf()};this.jf=function(){h.a("a35");var a=(window.name||(window.frameElement?window.frameElement.id:"")).substr(7),b=[],c=window.parent;h.a("ff6");try{b=c.document.getElementsByTagName("script")}catch(f){}h.a("ff6e");for(var c=b.length,e=0;e<c;e++)if(b[e]&&b[e].id&&b[e].id.substr(7)==a)return b[e];return null};this.te=function(){h.a("a36");return this.dvObj&&this.dataObj.impressionId&&this.dvObj.tags&&this.dvObj.tags[this.dataObj.impressionId]?
this.dvObj.tags[this.dataObj.impressionId].tagElement:null};this.Ae=function(){h.a("a37");var a=this.se(),b=null;a&&(b=this.Yd(a));return b};this.Yd=function(a){h.a("a38");var b={node:a,La:0};a=[];for(t=[];b||0<a.length;){try{var c;a:{var e=b.node;try{if(e&&-1!=x.indexOf(e.nodeName.toLowerCase())){c=!0;break a}}catch(l){}c=!1}if(c&&this.Pe(b.node)&&!this.qa(b.node)&&this.T(b.node))return b;if(b.La<=this.D.Ze){var f,q=b.node,v=b.La,b=[],u=q.parentNode;u&&-1==t.indexOf(u)&&(t.push(u),b.push({node:u,
La:v+1}));if(q.hasChildNodes())for(var m=0;m<q.childNodes.length;m++)q.childNodes[m]&&-1==t.indexOf(q.childNodes[m])&&1===q.childNodes[m].nodeType&&(t.push(q.childNodes[m]),b.push({node:q.childNodes[m],La:v+1}));var n,p=q,r=[],y=null;p&&p.parentNode&&(y=p.parentNode.firstChild);for(;y;)1===y.nodeType&&y!==p&&r.push(y),y=y.nextElementSibling||y.nextSibling;n=r;for(m=0;m<n.length;m++)n[m]&&-1==t.indexOf(n[m])&&1===n[m].nodeType&&(t.push(n[m]),b.push({node:n[m],La:v+1}));if(f=b)for(b=0;b<f.length;b++)a.push(f[b])}}catch(l){}b=
a.shift()}return{node:null}};return this}
function dv_CustomClientViewAssureService(b){function c(a){a&&($dv.registerEventCall($uid,{dvp_gmlad:1}),c=function(){})}function e(a){return{settings:a.settings,buckets:0,reported:!1,eventId:a.eventId,Ra:a.Ra,pb:a.pb,pc:a.pc}}this.dvObj=b.dvObj||window.$dv;this.impressionId=b.impressionId||window.$uid;this.b=new S;var l=[],m=null,n=null,h=null,p=null;this.dvObj&&this.dvObj.tags&&this.dvObj.tags[this.impressionId]&&(m=this.dvObj.tags[this.impressionId].cvmSettings,n=this.dvObj.tags[this.impressionId].billable,
h=this.dvObj.tags[this.impressionId].bprjct,p=this.dvObj.tags[this.impressionId].gmmod);this.xc=window.dv_cvmSettings||m||b.cvmSettings;this.Yb=window.dv_billable||n||b.billable;this.Ic=window.Kf||h||b.bprjct;this.Wc=window.Mf||p;this.ee=new e({settings:this.xc,eventId:6,Ra:["CustomViewabilityViewable"]});var r=this.b.Wa("rpv"),m=this.b.Pc().bgm;b.Bb=1==r&&1==m;this.Hc=new e({settings:this.Yb,eventId:17,Ra:b.Bb?["BillableViewedImpression"]:["BillableViewedImpression","GroupMPassedImpression"],pb:!0,
pc:!0});this.xc&&l.push(this.ee);this.Yb&&l.push(this.Hc);b.za=b.za||[];m={serverProperties:{projected:"bp",viewed:"bpv",viewedRate:"bpvr",error:"bperr"},reportQueryString:{projected:"isbprjct",measurems:"isbmms",viewedms:"isbvms",viewrate:"prjctbvr",error:"prjctber"}};this.Ic&&(m={serverData:this.Ic,projectionData:m,reportRTN:!0},b.za.push(m));m={serverProperties:{projected:"gmp",viewed:"gmpv",viewedRate:"gmpvr",error:"gmperr"},reportQueryString:{projected:"isgmmod",measurems:"isgmmims",viewedms:"isgmpims",
viewrate:"modgmvr",error:"modgmer"}};this.Wc&&(m={serverData:this.Wc,projectionData:m,reportRTN:!0},b.za.push(m));this.Xd=dv_InViewService;this.Xd(b);var t=this.Qb;this.Qb=function(a){a=t(a);for(var b=0;b<l.length;b++){var c=this.He(a,l[b]);this.xf(c,l[b]);this.Ud(l[b])}return a};var x=this.Sa;this.Sa=function(a,b){x(a,b);this.Yb&&1==this.cc&&(this.wa(["BillableMeasuredImpression"]),r?0==this.dataObj.Bb&&this.wa(["GroupMMeasuredImpression"]):1!=this.dataObj.irtf&&this.wa(["GroupMMeasuredImpression"]))};
this.He=function(a,b){"undefined"===typeof b.settings.focus||b.settings.focus||(a.g=a.ka);return a};this.xf=function(a,b){(!b.settings.measureType||"consecutive"==String(b.settings.measureType).toLowerCase())&&a.g<b.settings.adArea?b.buckets=0:a.g>=b.settings.adArea&&(!b.pb||1!=this.dataObj.irtf)&&(b.buckets+=this.da.interval);var e=0,h=0;a.A&&a.A.i&&(e=a.A.i.m||0,h=a.A.i.o||0);b.N=this.pa.$b(e,h,b.pc);c(b.N)};this.Ud=function(a){a.ef||a.pb&&1==this.dataObj.irtf||!(this.Od(a)||a===this.Hc&&a.settings&&
!a.settings.doNotReportViewedOnLargeAd&&a.N)||(this.fa.ba(a.eventId),a.Ra&&this.wa(a.Ra),a.ef=!0)};this.Od=function(a){return a.buckets>=a.settings.duration?!0:!1}}
function dv_InViewService(b){function c(){null===n.interval&&(n.interval=setInterval(n.we(),n.da.interval))}function e(){if(!1===n.ed){n.ed=!0;try{n.b.Ma.remove("load",arguments.callee,!1,element)}catch(a){}n.Gb();n.b.a("s41");n.pa=new aa(n.$d?n.$d:n.window,n.c,n.S,n.O,n.P,n.f.Kc,n.dvObj,n.impressionId);n.b.a("s42");n.Id();n.start()}}function l(a,b){return a.isReportingDisabled?new U:new T(a,b)}function m(a,b){n.b.Ma.add("click",function(){n.Ub(!0);$dv.registerEventCall(n.impressionId,"ad"==b?{dvp_csad:1}:
{dvp_csifr:1});n.b.Ma.remove("click",arguments.callee,!1,a)},!1,a,!1)}var n=this;this.gd=10;this.Wd=b.serverSettings&&b.serverSettings.jsVersion?b.serverSettings.jsVersion:"646";this.dvObj=b.dvObj||window.$dv;this.impressionId=b.impressionId||window.$uid;this._minor_version="0";this.b=new S;this.Ie=function(){for(var a=document.getElementsByTagName("script"),b=a.length,c,d=0;d<b;d++)if(c=a[d].src,/visit[.]js/.test(c))return c.substring(c.indexOf("?")+1)};this.ed=!1;var h={serverProperties:{projected:"p",
error:"perr",viewed:"pv",featurebit:"fb",viewedRate:"pvr"},reportQueryString:{projected:"isprjct",measurems:"ismms",viewedms:"isiabvms",viewrate:"prjctvr",error:"prjcter"}},p=!1,r=!1;this.za=b.za||[];(this.yf=b.prjct)&&this.za.push({serverData:b.prjct,projectionData:h,Lf:!0,Rf:["MeasurementCapabilityDetected","ProjectedMeasured","IabView","ProjectedAssignedViewed"],If:["MeasurementCapabilityDetected","ProjectedMeasured"]});h={serverProperties:{projected:"up",error:"uperr",viewed:"upv",viewedRate:"upvr"},
reportQueryString:{projected:"isuprjct",measurems:"isumms",viewedms:"isuiabvms",viewrate:"uprjctvr",error:"uprjcter"}};this.dvObj&&this.dvObj.tags&&this.dvObj.tags[this.impressionId]&&this.dvObj.tags[this.impressionId].uprjct&&this.za.push({serverData:this.dvObj.tags[this.impressionId].uprjct,projectionData:h});this.Ee=function(){var a="";this.dvObj&&this.dvObj.tags&&this.dvObj.tags[this.impressionId]&&this.dvObj.tags[this.impressionId].tagElement&&(a=this.dvObj.tags[this.impressionId].tagElement.src,
a=a.substring(a.indexOf("?")+1));return a};this.Uc=function(){return((new Date).getTime()+""+Math.floor(1E6*Math.random())).substr(0,16)};this.W=function(a,b){a=a.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]");var c=(new RegExp("[\\?&]"+a+"=([^&#]*)")).exec("?"+b);return c=c?c[1]:null};this.Fe=function(){var a=this.W("uid",this.ca);null==a?(a=this.Uc(),this.ca=this.ca+"&uid="+a):""==a&&(a=this.Uc(),this.ca=this.ca.replace("&uid=","&uid="+a));return a};this.sc=function(a,b,c,d){if(d&&d.insertBefore&&
d.firstChild&&(a=this.window.document.createElement(a))){for(var e in b)a[e]=b[e];for(e in c)a.style[e]=c[e];d.insertBefore(a,d.firstChild);return a}return null};this.Zd=function(){var a=this.dvObj.Enums.TrafficScenario;try{if(window.top==window)return a.OnPage;if(window.top.document.domain==window.document.domain)return a.SameDomain}catch(b){}return a.CrossDomain};this.S=this.dvObj.CommonData.Scenario||this.Zd();this.O={Y:this.dvObj.CommonData.BrowserId,ua:this.dvObj.CommonData.BrowserVersion};this.Z=
this.dvObj.Enums.BrowserId;this.aa=this.dvObj.Enums.TrafficScenario;this.cb="default";this.dataObj=b;this.window=b.tagWindow||parent.window||window;this.Jb=this.c=null;this.wc=this.Ta=!1;this.oc=!0;this.interval=null;this.ca=this.Ie();this.Da=this.Ee();b.serverSettings&&b.serverSettings.protocol&&b.serverSettings.protocol.indexOf("http");this.da=window.he||this.window.he||{interval:100,Ba:{"default":{time:null,Ma:["beforeunload","unload"],vd:9E5}}};this.kd={};var t=null;this.U=window.ge||this.window.ge||
{interval:1E3,$:6};h=b&&b.xd?b.xd:!1;b=b&&b.yd?b.yd:!1;!1!==h&&!1!==b&&(this.U.interval=h,this.U.$=b,$dv.registerEventCall(this.impressionId,{Ff:this.U.interval,Gf:this.U.$}));b=this.b.$a();this.ce={mb:12,ec:10,bb:30};this.P={Firefox:{X:115},Chrome:{X:89},Safari:{X:38},Explorer:{X:55},$e:500,$a:b,bb:30};var x=!1,a=0,d=[5,10,15];window.devicePixelRatio&&(this.P.Firefox.X=0);this.dataObj.spotXmode=this.dataObj.videoEnable||this.dataObj.detectVideoPlayer||this.dataObj.spotXmode;this.dvObj&&this.dvObj.tags&&
this.dvObj.tags[this.impressionId]&&this.dvObj.tags[this.impressionId].spotXmode&&(this.dataObj.spotXmode=this.dvObj.tags[this.impressionId].spotXmode);this.V=window.dv_configAdSize||this.window.dv_configAdSize||[{w:300,h:[100,250,268,600,618,850,1050]},{w:160,h:[600,800]},{w:120,h:[60,90,240,600,800]},{w:970,h:[66,90,250,30,415,550]},{w:728,h:[90,120]},{w:88,h:[31]},{w:700,h:[500]},{w:250,h:[60,250,300,360]},{w:180,h:[150,160,600]},{w:234,h:[60]},{w:468,h:[60]},{w:550,h:[480]},{w:125,h:[125]},{w:336,
h:[280,600,850]},{w:745,h:[90]},{w:954,h:[60]},{w:184,h:[90]},{w:800,h:[600]},{w:320,h:[360]},{w:1280,h:[100]},{w:640,h:[480,90]},{w:270,h:[460,202]},{w:613,h:[460]},{w:405,h:[303]},{w:950,h:[90]},{w:610,h:[100]},{w:272,h:[220]},{w:200,h:[200,446]},{w:220,h:[90]},{w:240,h:[133,400]},{w:960,h:[90]},{w:580,h:[400]},{w:750,h:[100,200,30]},{w:930,h:[180]},{w:980,h:[90,120]},{w:900,h:[240]}];this.dataObj.spotXmode&&(this.V.push({w:320,h:[240]}),this.V.push({w:400,h:[300]}),this.V.push({w:450,h:[338]}),
this.V.push({w:600,h:[800]}),this.V.push({w:640,h:[360]}),this.V.push({w:854,h:[480]}),this.V.push({w:500,h:[375]}));b&&(this.V.push({w:320,h:[50,100,480]}),this.V.push({w:300,h:[50,31]}),this.V.push({w:120,h:[20]}),this.V.push({w:168,h:[28]}),this.V.push({w:216,h:[36]}),this.V.push({w:292,h:[30]}));this.tb=this.Fe();this.dc=!1;this.Qa=function(a,b){this.window.Mc||(this.window.Mc=[]);this.window.Mc.push({caller:a,Jf:b})};this.startTime=(new Date).getTime();this.Td=4;this.Bc=0;this.lc=!0;this.logEvents=
{startMeasure:1,nonMeasurable:2,timeout:3,beforeunload:4,iabViewable:5,iabCustom:6,updateRTN:7,unload:8,errorlevel1:16,Df:17,interval:32};this.cc=!1;this.wd=function(){this.b.a("ie16");if(this.window.dv_logObject){var a=this.f.qe();this.window.dv_logObject[this.tb]=a}this.b.a("ie16e")};this.Kb=function(a){this.b.a("ie17");this.Kb=this.dc?function(a){this.f.qd(a);this.wd()}:function(a){this.f.qd(a)};this.Kb(a)};this.vc=function(a,b){this.vc=this.dc?function(a,b){this.f.pd(a,b);this.wd()}:function(a,
b){this.f.pd(a,b)};this.vc(a,b)};this.Gb=function(){this.b.a("s4");this.c=this.jb.ke(this.U.$);this.Jb=this.jb.Jb;!this.c&&this.S==this.aa.CrossDomain&&this.b.va(this.window)&&(this.U.$=0);if(this.c)this.kf(),this.f.cf(this.c),p||(m(this.c,"ad"),p=!0),r||this.S!=this.aa.CrossDomain&&this.S!=this.aa.SameDomain||(m(window.parent,"ifr"),r=!0),setTimeout(c,this.jb.Za?10:50);else if(0<this.U.$)this.U.$--,this.lf(),setTimeout(this.le(),this.U.interval);else{try{this.S==this.aa.CrossDomain&&(this.b.fd(this.window,
this.V)||this.b.va(this.window))?(this.c=this.b.Aa(this.window),this.f.od()):this.S==this.aa.SameDomain&&this.b.fd(this.window,this.V)?(this.c=this.b.Aa(window.parent),this.f.od(),this.be()):this.U.$=-1}catch(a){this.U.$=-1}setTimeout(c,10)}this.b.a("s4e")};this.be=function(){for(var a=this.window;a.parent!=a.top;)a=a.parent;this.b.a("ff26");for(var b=a.parent.document.getElementsByTagName("iframe"),c=b.length,d=0;d<c;d++)b[d].contentWindow==a&&(this.c=b[d],this.window=a.parent);this.b.a("ff26e")};
this.lf=function(){this.dataObj.I&&this.dataObj.Ua?this.f.qf():this.f.rf()};this.kf=function(){this.b.a("s9");this.Ta=!0;this.f.mf();this.b.a("s9e")};this.Vd=function(){this.dataObj.Xb=this.W("adsrv",this.ca)||"";this.dataObj.I=this.W("btreg",this.ca)||"";this.dataObj.hd=this.W("plcid",this.ca)||"";"8"==this.dataObj.Xb&&""==this.dataObj.btreg&&(this.dataObj.I=this.dataObj.plcid);this.dataObj.Ua=this.W("btadsrv",this.ca)||"";this.dataObj.Dc=this.W("adid",this.ca)||"";this.dataObj.tb=this.tb;this.dataObj.Te=
this.W("isbtregex",this.Da)||"";this.dataObj.ob=this.W("ctx",this.ca)||"";this.dataObj.nb=this.W("cmp",this.ca)||"";this.dataObj.Ve=this.W("lomd",this.Da)||"";this.dataObj.findclass=this.W("findclass",this.Da)||"";this.dataObj.displaynon=this.W("displaynon",this.Da)||"";this.dataObj.Jc=this.W("bsdvview",this.Da)||"";var a=this.W("bttag",this.Da)||"";this.dataObj.lb=0<a.length?a.split("|"):[];a=this.W("btattb",this.Da)||"";this.dataObj.Ka=0<a.length?a.split("|"):[]};this.jd=function(a){a=this.wa(a);
return 0<a.length?{tagServiceResult:a.join(",")}:{}};this.wa=function(a){if(!this.dvObj||!this.impressionId)return[];for(var b=[],c=0;c<a.length;c++){var d=this.dvObj.pubSub.publish(a[c],this.impressionId)||null;null!=d&&b.push(d)}return b};this.Bd=function(){this.dataObj.serverSettings&&this.dataObj.serverSettings.TKH&&(this.ca+="&TKH="+this.dataObj.serverSettings.TKH)};this.fe=function(){Array.prototype.indexOf=function(a){if(null==this)throw new TypeError;var b=Object(this),c=b.length>>>0;if(0===
c)return-1;var d=0;1<arguments.length&&(d=Number(arguments[1]),d!=d?d=0:0!=d&&Infinity!=d&&-Infinity!=d&&(d=(0<d||-1)*Math.floor(Math.abs(d))));if(d>=c)return-1;for(d=0<=d?d:Math.max(c-Math.abs(d),0);d<c;d++)if(d in b&&b[d]===a)return d;return-1}};this.inViewManager=function(){try{Array.prototype.indexOf||this.fe();this.Bd();this.Vd();this.f=new H(this.Wd,this.ce,this.dataObj);this.fa=l(this.dataObj,this.f);this.dataObj.isRTNsDisabled&&(this.wa=function(){return[]});this.dc=this.window.dv_logObject?
!0:!1;this.sf();this.jb=new ba(this.dataObj,this.V,this.window,this.f,this.S);var a=window.parent;"589953"==this.dataObj.ob&&"587351"==this.dataObj.nb||"589953"==this.dataObj.ob&&"616389"==this.dataObj.nb||"polite"==this.dataObj.Ve?(setTimeout(e,15E3),this.b.Ma.add("load",function(){setTimeout(e,1E3)},!1,a,!1)):e()}catch(b){var c=this;this.Ga(function(){c.Qa("inViewManager",b);c.f.gb("inViewManager",b);c.fa.ba(c.logEvents.errorlevel1)},"inViewManager",b)}};this.hb=function(a){this.b.a("ie20");-6!=
a.g&&(-3==a.g||-5!=a.g&&0>a.g&&-1==this.U.$)&&(this.yc(),this.hb=function(){})};this.yc=function(){this.fa.ba(this.logEvents.nonMeasurable);this.wa(["ImpressionNotMeasured"]);this.yc=function(){}};this.Sa=function(a,b){a.b.a("ie21");if(0<=b.g||-5==b.g&&-1>=a.U.$){if(a.dvObj&&a.impressionId){a.b.a("ie23");var c=a.jd(["MeasurementCapabilityDetected","GeoMeasured"]);a.b.a("ie24");a.fa.ba(a.logEvents.startMeasure,c)}else a.fa.ba(a.logEvents.startMeasure);a.cc=!0;a.Sa=function(){};a.hb=function(){}}a.b.a("ie22")};
this.Ub=function(a){this.b.a("ie25");if(this.f.Qc()||a&&!0===a)this.b.a("ie27"),this.dvObj&&this.impressionId?(this.b.a("ie28"),a=this.jd(["IabView","GeoViewed"]),this.b.a("ie29"),this.fa.ba(this.logEvents.iabViewable,a)):this.fa.ba(this.logEvents.iabViewable),x=!0,this.Ub=function(){};this.b.a("ie26")};this.acumulateViewableTime=function(b){if(x&&this.f.Qc())for(a+=b,b=0;b<d.length;b++)null!=d[b]&&a>=1E3*d[b]&&(this.wa(["viewd"+d[b]+"sec"]),d[b]=null)};var g="hidden",k=0;this.hasFocus=function(){vis=
["hidden","webkitHidden","mozHidden","msHidden","oHidden"];for(hiddenProp in vis)if(vis[hiddenProp]in document){g=vis[hiddenProp];break}var a=1==this.b.Wa("fcs"),b=!1;try{this.b.Ya(this.window),b=!0}catch(c){}var d=!1;try{this.b.Ya(this.window.top),d=!0}catch(c){}var e=null,e=a&&b&&this.O.Y==this.Z.IE?function(){var a=n.b.Ya(n.window);n.S==n.aa.OnPage&&(a=a&&n.oc);return a}:a&&d?function(){var a=!0,a=n.b.Ya(n.window.top);n.S==n.aa.OnPage&&(a=a&&n.oc);return a}:"undefined"!==typeof document[g]?function(){return!n.window.document[g]}:
d?function(){return n.b.Ya(n.window.top)}:function(){return!0};this.hasFocus=function(){try{return e()}catch(a){k++,5<=k&&(this.hasFocus=function(){return!0})}return!0};return this.hasFocus()};this.jc=function(a){var b=a.pa.ue();a.b.a("ie12");0>b.g&&this.f.Ib(Math.abs(b.g));null==this.c||-3==b.g||a.hasFocus()||(b.g=0,this.f.Ib(9));a.b.a("ie13");return t=b};this.Qb=function(a){a.b.a("ie1");var b=a.c?a.c.ub||a.window:a.window;a.pa.c=a.c;a.pa.window=b;a.b.a("ie2");b=a.jc(a);a.Ta&&(-1==b.g||-2==b.g)&&
-1<=a.U.$&&(a.md(a),a.Gb());a.b.a("ie3");-5==b.g&&(a.U.$--,a.f.rd(),a.Pa||(a.Pa=function(b){b=a.pa.xb(b);a.f.eb(b)}));a.b.a("ie4");a.Pa&&0<b.g&&(a.Pa(b),a.Pa=null);a.b.a("ie5");if(a.Ta&&!a.wc){a.wc=!0;var c=a.pa.xb(b);a.f.eb(c)}-5==b.g&&-1<=a.U.$&&(a.md(a),a.Gb(),b=a.jc(a),-5==b.g&&0<a.U.$&&a.f.gf());a.b.a("ie6");a.vc(b,a.da.interval);a.b.a("ie7");a.Kb(b);a.b.a("ie8");a.f.td(b.ha);a.hb(b);a.b.a("ie9");a.Sa(a,b);a.b.a("ie10");a.Ub();a.b.a("ie11");a.acumulateViewableTime(a.da.interval);a.b.a("ie12");
return b};this.md=function(a){a.Ta=!1;a.c=null;a.jb.ff();a.pa.Je()};this.we=function(){this.b.a("s26");var a=this;return function(){try{a.Qb(a)}catch(b){a.Ga(function(){a.Bc<a.Td&&(a.Bc++,a.Qa("getIntervalCallback",b),a.f.gb("getIntervalCallback",b),a.fa.ba(a.logEvents.errorlevel1))},"getIntervalCallback",b)}}};this.Tc=function(a){var b=this;return function(){b.Ga(function(){b.fa.ba(b.logEvents[a])},"getReportEventCallback")}};this.le=function(){var a=this;return function(){a.Ga(function(){a.Gb();
a.c||a.f.Hb()},"getAdLocateCallback")}};this.Xa=function(){var a=this;return function(b){try{b||(b=a.window.event),a.oc="blur"==b.type||"focusout"==b.type?!1:!0}catch(c){a.Ga(function(){a.Qa("getFocBluEventCallback",c);a.f.gb("getFocBluEventCallback",c);a.fa.ba(a.logEvents.errorlevel1)},"getFocBluEventCallback",c)}}};this.Hd=function(){try{if(this.dvObj&&this.impressionId&&this.dvObj.tags[this.impressionId]){var a=this;this.dvObj.tags[this.impressionId].getViewabilityData=function(){try{for(var b=
a.f.re().slice(0),c=0;c<b.length;c++)void 0===b[c]||null===b[c]?b[c]=0:isNaN(b[c])||(b[c]/=1E3);var d={};d.bucket_0=b[0];d.bucket_1_9=b[1];d.bucket_100=b[11];for(c=2;10>=c;c++)d["bucket_"+(10*(c-1)).toString()+"_"+(10*c-1).toString()]=b[c];return{buckets:d,isAdMeasureable:a.cc,totalPageTime:(a.f.hc()-a.f.De())/1E3,notApplicableTime:a.f.Sc()/1E3}}catch(e){return{}}}}}catch(b){}};this.Id=function(){try{if(this.dvObj&&this.impressionId&&this.dvObj.tags[this.impressionId]){var a=this.dvObj.tags[this.impressionId];
a.VA||(a.VA={});a.VA.getVisibilityResult=function(){var a={};a.perc=t.g;0<=t.g&&t.A&&t.A.i&&(a.adWidth=t.A.i.o,a.adHeight=t.A.i.m);return a};a.VA.getAdElem=function(){return n.c}}}catch(b){}};this.Hd();this.start=function(){this.b.a("s35");this.af(this);var a;this.da&&this.da.Ba&&this.da.Ba[this.cb]&&(a=this.da.Ba[this.cb].Ma);if(a)for(var b=a.length,c=0;c<b;c++)this.kd[a[c]]=this.Tc(a[c]),this.Ja(this.window,a[c],this.kd[a[c]]);this.uf();this.da&&this.da.Ba&&this.da.Ba[this.cb]&&this.da.Ba[this.cb].vd&&
setTimeout(this.df(),this.da.Ba[this.cb].vd)};this.df=function(){var a=this;return function(){a.Tc("timeout")();clearInterval(a.interval);a.fa.ba=function(){}}};this.af=function(a){try{var b=a.jc(a);-5==b.g&&(this.f.rd(),this.Pa||(this.Pa=function(b){b=a.pa.xb(b);a.f.eb(b)}));if(a.Ta)if(this.wc=!0,-5!=b.g){var c=a.pa.xb(b);a.f.eb(c)}else a.f.eb("true");a.f.td(b.ha);var d=a.pa.ne(b,a.f.Sc());a.f.pf(d);a.f.sd(b.g);a.Kb(b);a.hb(b);a.Sa(a,b)}catch(e){a.Ga(function(){a.Qa("onStartReport",e);a.f.gb("onStartReport",
e);a.fa.ba(a.logEvents.errorlevel1)},"onStartReport",e)}};this.uf=function(){this.Ja(this.window,"blur",this.Xa());this.Ja(this.window,"focus",this.Xa());this.Ja(this.window.document,"click",this.Xa());this.Ja(this.window.document,"mousedown",this.Xa());this.Ja(this.window.document,"mouseup",this.Xa())};this.Ja=function(){function a(b,c,d){a=b.addEventListener?function(a,b,c){a.addEventListener(b,c,!1)}:b.attachEvent?function(a,b,c){a.attachEvent("on"+b,c)}:function(a,b,c){a["on"+b]=c};a(b,c,d)}return function(b,
c,d){a(b,c,d)}}();this.stop=function(){};this.sf=function(){this.b.a("ff24");this.S==this.aa.CrossDomain?this.b.va(this.window)||this.b.nc(this.window)||this.b.yb()||this.b.zb(this.S,this.O,this.dvObj)||(this.O.Y!=this.Z.Firefox&&this.O.Y!=this.Z.IE?this.f.tf():this.O.Y==this.Z.Firefox&&"undefined"===typeof this.window.mozInnerScreenX&&this.f.tc()):window.document.body.getBoundingClientRect||this.f.tc();this.lc=this.f.Kc();this.b.a("ff24e")};this.Ga=function(a,b,c){try{a()}catch(d){try{0<this.gd&&
(this.gd--,a=c||d,b=b||"unknown caller",this.Qa(b,a),this.f.gb(b,a),this.fa.ba(n.logEvents.errorlevel1))}catch(e){}}};return this}
try{window.dv_InViewService=dv_InViewService;dv_InViewService.prototype.inViewManager=dv_InViewService.prototype.inViewManager;var ViewAssureBootstrapper=function(b){$dv.tags[$uid].gmmod||$dv.tags[$uid].cvmSettings||$dv.tags[$uid].billable||b.cvmSettings||b.billable?(new dv_CustomClientViewAssureService(b)).inViewManager():(new dv_InViewService(b)).inViewManager()};if("function"===typeof window.IVCallback)IVCallback(ViewAssureBootstrapper);else for(var Y=[window.$dvbs,window.$dvbsr],Z=0;Z<Y.length;Z++){var dvObj=
Y[Z];if(dvObj&&"object"===typeof dvObj&&"function"===typeof dvObj.getTagObjectByService){var tagObject=dvObj.getTagObjectByService("avs646");if(tagObject){var serviceParams=tagObject.services.avs646;serviceParams&&serviceParams.params&&ViewAssureBootstrapper(serviceParams.params)}}}}catch(b){};
